yast/yast-add-on

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/inst_add-on.rb
The registration module directly called the add-on module, that made some troubles as some parts of the registration module were skipped when add-on restarted the workflow from the next step.
That add-on call has been removed from the registration module, now it is called from the `control.xml` file so we can revert the patch and restart the workflow again. The restart is needed to activate the newly added steps from `installation.xml`.
@jsuchome has tested the patch with Cloud6 addon (https://bugzilla.suse.com/show_bug.cgi?id=949185#c9), I have tested the patch with some addons from SCC (just to make sure it still works properly).
> Restart the workflow to activate steps added via installation.xml (bsc#949185)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/autoyast-rnc/add-on.rnc
Fix for https://bugzilla.suse.com/show_bug.cgi?id=976457, the profile does not validate because of the `priority` value in the profile:
```xml
<priority config:type="integer">50</priority>
```
The `priority` key is handled in the [`Import` method](https://github.com/yast/yast-packager/blob/master/src/modules/AddOnProduct.rb#L1919), but not described in the profile schema.
- 3.1.13
> Added missing "priority" tag in the AutoYaST schema (bsc#976457)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/add-on_auto.rb
I have implemented it like it is described in the official documentation:
https://www.suse.com/documentation/sles-12/singlehtml/book_autoyast/book_autoyast.html#Software.Selections.additional
So, add-on signature handling will "win" before the general signature handling.
> Do not reset add-on signature handling by the general sign. handling

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
This goes along with some changes in yast-package in a separate PR (https://github.com/yast/yast-packager/pull/172)
Compare the screenshots to see the matching layout.
Please note that this PR only affects the general dialog layout (Title on the left) - the order of the labels and checkboxes is changed in yast-package.
>  	Fix layout of Add-On screen (bsc#951720)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/add-on_auto.rb
[bsc#972046](https://bugzilla.suse.com/show_bug.cgi?id=972046)
> AutoYaST: Handling variables in add-on URLs

- .gitignore
- .travis.yml
- Dockerfile
- This is basically a copy from `master`
- Only `yastdevel/ruby:sle12-sp2` is used instead of `yastdevel/ruby`
- Testsuite and .gitignore updated
> Docker sle12 sp2

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
If the repository comes from a multi module medium then the repository subdirectory should be displayed as well.
That's important esp. if you add several repositories, the same URL is confusing.
> Display also the repository path in the URL column (fate#323886)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- Allow preselecting the add-on URL schema and hiding the *"I would like to install an additional Add On Product"* check box from the external code.
- Related to [FATE#323163](https://fate.suse.com/323163)
- 4.0.1
> Allow pre-setting the defaults for the new addon URL (FATE#323163)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- Fixes [openQA regression](https://openqa.suse.de/tests/1240331#step/addon_products_sle/8) caused by the previous fix
- After pressing the *Add* button the checkbox should not be displayed
> Fixed checkbox behavior (bsc#1065843)

- .gitignore
- README.md
- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- test/repositories_include_test.rb
- test/test_helper.rb
- All new added repositories are now processed, not only one of them
- See https://bugzilla.suse.com/show_bug.cgi?id=1062813
- Added initial unit test support
- Added some simple unit tests
- Enabled Coveralls (code coverage)
- Also tested manually in a full installation (see the screenshots below)
- Some additional cleanup
If user selected several addons from a multi repository medium in this dialog:
Then the addon summary listed only one of them:
And only that product was selected to install:
After applying the fix all addons are displayed in the table:
And all products are selected to install:
> Fixed using a multi repository medium (bsc#1062813)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- test/repositories_include_test.rb
- The `AddOnProduct.src_id` value must be set before calling `AddOnProduct.DoInstall`
- The `AddOnProduct.DoInstall` must be called for each addon separately (so it can correctly integrate the optional `installation.xml` file for each addon)
- 4.0.5
> Fixed a crash when when adding an addon (bsc#1074766)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/inst_add-on.rb
- src/include/add-on/add-on-workflow.rb
https://fate.suse.com/324656
https://trello.com/c/COqWRVeq
> Possibly interactive workflow with addon= (fate#324656)

- test/test_helper.rb
Forgotten in PR #52.
After running `rake osc:build` it seems that now both, Travis and Jenkins, will be happy :)
> Mock missing dependency necessary to run tests

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
This PR is a refactorization of auto add-on client, following the approach suggested by @imobachgs and @jreidinger in #52 and discarding the [first idea about refactoring only the #write method](https://github.com/dgdavid/yast-add-on/commit/8517e3fa558ff320ef5bdf76d9470b7aaf602de9).
Help is needed to finish it, especially with the test which probably needs improve a lot. Also, help with naming and documentation is welcome.
I will do a self-review to write down some doubts in place.
> Refactor add on auto client

- package/yast2-add-on.spec
The build of the packages is failing since the refactorization made in #54, this PR just adds the missing dependency.
> Required autoyast2-installation for building the package

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
It seems that `AutoInstall` is not needed at all, but the import of `AutoinstSofware` module was missing. The module was stubbed and that is why the test was not failing.
Removed again the autoyast2-installation build dependencies for speeding up the tests.
> AddOn auto client: Fixes import dependencies

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/add-on_auto.rb
- src/lib/add-on/clients/add-on_auto.rb
Fix detected errors introduced in the AddOn auto client refactorization
* Use `#run` instead the former `#main`
* Bring back missed imports
---
Related to https://trello.com/c/48C6zsLV
> Fix AddOn auto client

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
Related to https://bugzilla.suse.com/show_bug.cgi?id=1108139
---
During [the AddOn auto client refactorization](https://github.com/yast/yast-add-on/pull/54) a typo was introduced at the time to get the repo name, asking for `media` key instead of the right `media_url`. In addition, also the default value for `.fetch` was forgotten.
This PR fix those bugs and the implied test has been adapted a little to ensure a minimum coverage of the `preferred_name_for` method.
> Fix the repo name selection

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- test/test_helper.rb
- [Bug #1117492](https://bugzilla.suse.com/show_bug.cgi?id=1117492)
- Originally the code displayed a new dialog on top of the current one. After closing the dialog the previous one was displayed for a short while, before it got replaced by the content of the next dialog.
- This is the real fix for the bug, the previous one was not enough when going back
- The referenced bug [#305788](https://bugzilla.suse.com/show_bug.cgi?id=305788) does not seem to be valid anymore, I did not see any problem after removing that 11+ years old fix
- Originally the partitioning dialog was displayed for a short while after going back in the add-on dialog
- Now the partitioner dialog is not displayed anymore
- Additionally fixed testsuite to not display PolicyKit popup
>  Fixed displaying previous dialog content (bsc#1117492)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
When user refuses an addon's EULA (doing click in "Next" without check the _I Agree to the License Terms._) the installation is completely aborted.
* https://bugzilla.suse.com/show_bug.cgi?id=1114018
* https://trello.com/c/Kc9mRVpB
In spite of in the current code there is an intentional (and broken) behavior to
> **just go ahead _refusing_ the license and not installing/registering the addon**, according to the message shown to the user.
<details>
<summary>Show/hide screenshot</summary>
---
<small>The message shown to the user, from an SLE-12 Screenshot (still being the same)</small>
---
</details>
To do that, it has been necessary to update `yast2-packager` too (see https://github.com/yast/yast-packager/pull/456), in order to support "refuse" as a cancel action. Otherwise, it is not …
> [SLE-15-SP1] Do not abort the installation when an addon EULA is refused

- package/yast2-add-on.spec
> Forgotten in 08fe350872915c3c8772d2776491b8a27cfec6ed
To be able to [_Do not abort the installation when an addon EULA is refused_](https://github.com/yast/yast-add-on/pull/78), the `yast2-packager >=` [`4.1.47`](https://github.com/yast/yast-packager/pull/456) is required.
> Update yast2-packager dependency

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
When user refuses an addon's EULA (doing click in "Next" without check the _I Agree to the License Terms._) the installation is completely aborted.
* https://bugzilla.suse.com/show_bug.cgi?id=1114018
* https://trello.com/c/Kc9mRVpB
In spite of in the current code there is an intentional (and broken) behavior to
> **just go ahead _refusing_ the license and not installing/registering the addon**, according to the message shown to the user.
<details>
<summary>Show/hide screenshot</summary>
---
<small>The message shown to the user, from an SLE-12 Screenshot (still being the same)</small>
---
</details>
To do that, it has been necessary to update `yast2-packager` too (see https://github.com/yast/yast-packager/pull/456), in order to support "refuse" as a cancel action. Otherwise, it is not …
> [master] Do not abort the installation when an addon EULA is refused

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/autoyast-rnc/add-on.rnc
- src/clients/add-on_proposal.rb
- src/lib/add-on/clients/add-on_auto.rb
- src/modules/AddOnOthers.rb
- test/addon_others_test.rb
- test/y2add_on/clients/add-on_auto_test.rb
With that PR we would have that solution in the AY configuration file.
```xml
<add-on>
<add_on_others config:type="list">
<listentry>
<alias>yast_head</alias>
<media_url>https://download.opensuse.org/repositories/YaST:/Head/openSUSE_Leap_15.1/\</media_url>
<name>Yast head</name>
<priority config:type="integer">99</priority>
<product_dir>/</product_dir>
</listentry>
</add_on_others>
<add_on_products config:type="list">
<listentry>
<media_url>dvd:/?devices=/dev/sr1</media_url>
<product>sle-module-desktop-applications</product>
<product_dir>/Module-Desktop-Applications</product_dir>
</listentry>
<listentry>
<media_url>dvd:/?devices=/dev/sr1</media_url>
<product>sle-module-basesystem</product>
<product_dir>/Module-Basesystem</product_dir>
</listentry>
</add_on_products>
</add-on>
```
The …
> User defined add-ons

- package/yast2-add-on.changes
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
- When serving the SLE15 modules via a local FTP server AutoYaST gets errors when adding the modules (server timeout errors)
- See https://bugzilla.suse.com/show_bug.cgi?id=1141127
- In reality these are "too many connections" errors, the server has a low limit for the maximum number of connections from the same IP
- We need to call the `Pkg.SourceReleaseAll` call to release the libzypp media accessors
- Tested manually with an FTP server configured with max. 3 connections per IP, AutoYaST could add 15 repositories (modules) without any problem.
- Added an unit test
> Release the sources to avoid using up all server connections 

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- When installing from the offline medium we should directly offer the modules and extensions available on the installation medium.
- 4.2.7
This URL/repository type selection dialog is skipped:
And directly the modules and extensions from the installation medium are displayed:
Which is more straight forward and easier for user.
> Automatically offer the addons from the offline medium (jsc#SLE-7101)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- Display the human readable product names instead of the internal identifiers in the add-on products summary table
- https://bugzilla.suse.com/show_bug.cgi?id=1153663
- 4.2.8
> Display the human readable product names (bsc#1153663)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
> the installer does not go back beyond the "Add On Product" step
* Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1156528
* Trello: https://trello.com/c/tOe99fFW/1457-sles15-sp2-p2-1156528-the-installer-does-not-go-back-beyond-the-add-on-product-step
Changes made in https://github.com/yast/yast-add-on/pull/78 to not abort the installation when an EULA add-on is refused [_breaks_](https://github.com/yast/yast-add-on/blob/fbb1c47d36269ebcc8f9eca988b93c102e6b41bb/src/include/add-on/add-on-workflow.rb#L1030) the sub-workflow without propagating the action first when the user is going _:back_.
Propagate the user input properly, without forcing to break the workflow. Actually, it [is already being interrupted](https://github.com/yast/yast-add-on/blob/fbb1c47d36269ebcc8f9eca988b93c102e6b41b …
> Fix the sub-workflow user input handling 

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
> the installer does not go back beyond the "Add On Product" step
* Bugzilla: https://bugzilla.suse.com/show_bug.cgi?id=1156528
* Trello: https://trello.com/c/tOe99fFW/1457-sles15-sp2-p2-1156528-the-installer-does-not-go-back-beyond-the-add-on-product-step
Changes made in https://github.com/yast/yast-add-on/pull/78 (and https://github.com/yast/yast-add-on/pull/79)  to not abort the installation when an EULA add-on is refused [_breaks_](https://github.com/yast/yast-add-on/blob/fbb1c47d36269ebcc8f9eca988b93c102e6b41bb/src/include/add-on/add-on-workflow.rb#L1030) the sub-workflow without propagating the action first when the user is going _:back_.
Propagate the user input properly, without forcing to break the workflow. Actually, it [is already being …
> [SLE-15-SP2] Fix the sub-workflow user input handling

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/vendor.rb
- src/include/add-on/add-on-workflow.rb
- test/repositories_include_test.rb
Replacing old Pkg.ResolvableProperties()and Pkg.ResolvabeDependencies() calls by Y2Packager::Resolvable.any? and Y2Packager::Resolvable.find in order to save memory.
> Decreasing required memory

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1158247
- Fixed reading the products, `Y2Packager::Resolvable.find` expects a `Hash` parameter
- Some additional cleanup
- We do not need the shorten the license text, the new `Y2Packager::Resolvable` objects do not load the license text by default, the license is lazy loaded after calling the `.license` method
- Removed that useless `deep_copy` and `Builtins.maplist` calls
- Tested manually, cloning now does not crash
- 4.2.11
> Fixed crash when cloning the system (bsc#1158247)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- test/add-on-workflow_test.rb
The recent changes enable optional registration also on the Full medium. But we need to avoid mixing the add-ons from SCC (or RMT) with the add-ons from the Full DVD medium. We need to skip the automatic add-ons selection from the medium when the system is registered. 
If the system is registered skip that automatically displayed add-on dialog.
- 4.2.12
> Improved adding add-ons on the Full medium (jsc#SLE-7101)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/autoyast-rnc/add-on.rnc
trello: https://trello.com/c/HkFkUQHj/1791-3-continue-with-new-xml-parser-xml-validation
depends on yast/yast-autoinstallation#598
Agreed to postpone for now that trang and jing travis validation to not delay even more new xml parser.
bsc: https://bugzilla.suse.com/show_bug.cgi?id=1170886
> allow optional string and map types

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/modules/AddOnOthers.rb
- test/addon_others_test.rb
Trello: https://trello.com/c/jzih5O43/1928-8-export-registered-add-ons-properly
Related to: https://github.com/yast/yast-registration/pull/502
Do not export those add-ons that have been registered. They should be listed in the `<suse_register/>` section of the profile. This code has been manually tested but it is still a WIP.
> Do not export registered add-ons

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/autoyast-rnc/add-on.rnc
Allows to use the new `type` and `t` attributes to specify the type of the `add_on_products` and `add_on_others` sections.
Trello: https://trello.com/c/WtDObsGz/1983-3-tw-1174424-build-20200720-autoyast-profile-doesnt-validate
Bug report: https://bugzilla.opensuse.org/show_bug.cgi?id=1174424
> Fix add-on section schema

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
- This is similar fix to https://github.com/yast/yast-packager/pull/533, see that PR for more details
- I do not know when exactly this bug happens and what's the real problem, I found the problematic place by grepping for `Pkg.SourceEditSet`
- As metioned above, I could not easily test the bug fix (and it's AutoYaST...)
- But there is an unit test for that so hopefully that's enough
- Either it fixes the problem or we get a bug report with more details later
> Fixed regression in the add-on repository names (bsc#1175374)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- test/repositories_include_test.rb
- YaST skipped the add-on selection on the Full medium when an add-on was already present to avoid asking user several times when going back and forth.
- But when a DUD is used it also contains an add-on internally and then the dialog was skipped.
- The solution is to store a flag that the dialog has been already displayed, do not check the current add-ons as we cannot detect which come from the Full medium.
- See https://bugzilla.suse.com/show_bug.cgi?id=1174562
Originally the add-on selection dialog was skipped, after skipping the registration the add-on overview was displayed showing only the DUD add-on.
With the fix the add-on selection from the Full medium is displayed and later the selected add-ons are visible in the table.
> Display the add-on selection dialog even when a DUD add-on is present

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- test/test_helper.rb
Since SLE-15, firewalld is the default firewall and the YaST configuration of SuSEFirewall2 has been dropped but we are still trying to import it
- see https://github.com/yast/yast-yast2/pull/806
Drop SuSEFirewall2 references.
> Remove SuSEFirewall2 references

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- test/y2add_on/clients/add-on_auto_test.rb
This pull request in yast-yast2 (https://github.com/yast/yast-yast2/pull/1122) changed the behavior during unit tests of `Yast::Report` and `Yast2::Popup`, making necessary to add some extra mocking to prevent YaST from trying to open windows during the test execution.
As far as we know, that affected the test-suites of: yast-autoinstallation, yast-add-on, yast-bootloader, yast-configuration-management, yast-dns-server, yast-installation, yast-kdump, yast-network, yast-nfs-client, yast-ntp-client, yast-storage-ng, yast-country, yast-firewall, yast-nfs-server, yast-nis-client, yast-pam, yast-security, yast-services-manager, yast-samba-server, yast-packager, yast-registration and yast-sysconfig.
This should fix the problem for this repository.
> Adapt unit test to recent changes in Yast::Report

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
When an add-on repository is disable (e.g., after finishing the installation the DVD repositories get automatically disabled), yast2 add-on shows the "Unknown URL" label as URL, which is a bit misleading.
* https://bugzilla.suse.com/show_bug.cgi?id=1188635
* https://trello.com/c/BNkRWGoz/4835-sles15-sp4-p2-1188635-addon-url-in-yast2-addon-package-enhanceable
To use a more generic text "Not found in enabled repositories".
Additionally, 
* If the add-on is not found in enabled repositories, the `Repository URL` is not shown anymore in the details box
* the code to build the _additional_ details has been _refactored_ (just killed a bunch of `Builtins`)
| Before | After |
| - | - |
| ![Text shown before](https://user-images.githubusercontent.com/1691872/130104577-838a9ca8-ad6b-4fe9-ba2d-4c28f7 …
> Improve UX using generic error message for unknown repo URL

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
The autoinstallation client crash when there is nothing to import. E.g., when the profile contains an empty `<add-on />` section
```ruby
NoMethodError:
undefined method `fetch' for nil:NilClass
```
* https://trello.com/c/CDV7zhjG
* https://bugzilla.suse.com/show_bug.cgi?id=1189154
Do not try to _fetch_ add-on products from `nil`. I.e., does nothing when #import receives `nil`
* Fixed and updated unit testing
Better to review commit per commit, since there are two _noisy_ commits.
> [SLE-15-SP3] Auto client: do not crash when there is nothing to import 

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
https://trello.com/c/gT8nMq7O/2635-3-featureshouldhave-handle-more-gracefully-when-libyui-libraries-are-missing
- https://jira.suse.com/browse/SLE-20346
- https://jira.suse.com/browse/SLE-20462
- Main PR: https://github.com/yast/yast-yast2/pull/1194
- https://github.com/yast/yast-packager/pull/578
- https://github.com/yast/yast-online-update/pull/36
If the "pkg" UI extension plug-in is not available (usually because it's not installed), offer to install it.
In this module this is only done when the user clicks on the "Run Software Manager" button; everything else can easily be done without that "pkg" UI extension.
For more information, see https://github.com/yast/yast-packager/pull/578
> add_on: Check for -pkg UI Plug-In and Prompt to Install it if Needed

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1191491
- Related to https://github.com/yast/yast-packager/pull/594
- The `add-on` module works a bit differently than the `repositories` module, if the repository name is not set it uses the product name in the repository
- This restores the original behavior after applying https://github.com/yast/yast-packager/pull/593
> Properly set the custom repository name (#1191491)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/include/add-on/add-on-workflow.rb
- https://bugzilla.suse.com/show_bug.cgi?id=1193339
- The `subscription-tools` package is not present in SLE15 anymore
- 4.4.5
> Drop support for subscription-tools (bsc#1193339)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
Four years ago, while [refactoring the add-on auto client](https://github.com/yast/yast-add-on/pull/54), a line of code [for restoring the unexpanded repository URL](https://github.com/yast/yast-add-on/pull/28#issuecomment-291116098) was drop.
The reason behind removing that line was that, apparently, [it did nothing where it was](https://github.com/yast/yast-add-on/pull/54#pullrequestreview-130681351). However, recently we got a quite detailed [bug report](https://bugzilla.suse.com/show_bug.cgi?id=1194851) about AutoYaST replacing $releasever in add-on repos with the version number.
After doing a bunch of manual testing, the line has been placed after creating the repo and installing the products, because in where it was it actually does not work.
* Added unit test (in an attempt to …
> [SLE-15-SP1] Restores unexpanded repository URL

- test/y2add_on/clients/add-on_auto_test.rb
Using "times" receive count instead of its "time" alias, which was introduced in RSpec Mocks 3.9[1] (and SLE-15-SP1 is using 3.7).
No version bump/changelog update required since it is actually part of #120
[1] https://github.com/rspec/rspec-mocks/blob/main/Changelog.md#390--2019-10-07
> Fix unit test

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
The same as #120 and #122, but for `SLE-15-SP2`. 
In short, it fixes restoring the unexpanded repository URL to have the original URL in the saved _/etc/zypp/repos.d_
> [SLE-15-SP2] Restores unexpanded repository URL

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/add-on-workflow_test.rb
- test/test_helper.rb
- test/y2add_on/clients/inst_add-on_test.rb
- Enable RSpec verifying doubles in unit tests to ensure that the mocked methods really exist
> Enable RSpec verifying doubles (bsc#1194784)

- .rubocop.yml
- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
The same as #120/#122, and #121, but for `SLE-15-SP3`. 
In short, it fixes restoring the unexpanded repository URL to have the original URL in the saved _/etc/zypp/repos.d_
> [SLE-15-SP3] Restores unexpanded repository URL

- .rubocop.yml
- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
The same as #120/#122, #121, and #123 but for `SLE-15-SP4`. 
In short, it fixes restoring the unexpanded repository URL to have the original URL in the saved _/etc/zypp/repos.d_
> Restores unexpanded repository URL

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/clients/add-on.rb
- src/clients/vendor.rb
- When running the `add-on` module in the management container it does not display the installed add-ons properly.
- The problem is in the libzypp initialization
- The fix is similar to https://github.com/yast/yast-packager/pull/621, do not hardcode the target path
- The `grep` command found a similar problem in the `vendor` client, though I could not test the fix, I do not have any testing vendor CD.
- Tested manually
Without the patch the module loads the add-ons from the container itself, it obviously does not contain any addons:
With the patch the libzypp is properly initialized in the target and the installed add-ons are properly displayed:
> Support managing system in a chroot (bsc#1199840)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- https://trello.com/c/CAytlL3W
- https://jira.suse.com/browse/SLE-22578
- https://jira.suse.com/browse/SLE-24584
Support new `repo` URI scheme that works relative to the installation medium.
- https://github.com/yast/yast-packager/pull/624
> support 'repo' scheme for add-ons (jsc#SLE-22578, jsc#SLE-24584)

- package/yast2-add-on.changes
- package/yast2-add-on.spec
- src/lib/add-on/clients/add-on_auto.rb
- test/y2add_on/clients/add-on_auto_test.rb
- Fixes a problem with `<media_url><![CDATA[ relurl:// ]]></media_url>` in the AutoYaST profile (note the spaces around the URL). That is read as " relurl:// " string which is an invalid URL.
- See https://bugzilla.suse.com/show_bug.cgi?id=1205928
- Related to https://github.com/yast/yast-yast2/pull/1243 which keeps the spaces
- Strip the white space from the URL
- Added a new unit test
- Tested manually, installation works fine with `<![CDATA[ relurl:// ]]>`
> Ignore extra white space in URL (bsc#1205928)
